### ISSUE TITLE
Add the ability to be used on multiple layers

### ISSUE THREAD

**Issue by frogman-pal** [GEG-fairbear8974/PSX-Style-Camera-Shader#1]
Example: For if your game has a different viewport for items that you hold, like flashlights or weapons. If you apply to the layer, it doesnt take the transparency into effect I believe and creates a black background.

**Comment by immaculate-lift-studio** [comment]
This shader is designed to be used within a single viewport, if you wanted it to be rendered across multiple viewports or layers you would need to apply this shader again to that layer/viewport. However if this is an issue related to transparent materials/objects not showing up in the shader, my readme has a workaround near the bottom. Essentially, you have to make sure the objects with transparency are rendered after the shader by setting the layer to a higher number than where the shader renders. Unless you've changed a lot of layers in your project, setting it to 1 or 2 is usually sufficient.

I know you just closed this out, but if that doesn't help, please give me more information so I can help you out.

**Comment by frogman-pal** [comment]
~~Sorry I didn't mean to close it, more so meant to delete it because I sort of figured out how to do it? I just put the environment that I'm using for the main camera onto the 2nd viewport camera, and that removed the whole black transparency thing. So I think a workaround works only if your two cameras use the same environment ^^~~

~~edit: lol.. nvm, that allows clipping on the 2nd viewport models~~

edit edit: it seems like I accidently just allowed the other stuff to render on that 2nd viewport, so none of what I said is valid lol
